#!/bin/bash

# Script qui ouvre la documentation
# Appel avec : $ sh documentation
# ou pour regénérer : $ sh documentation actualiser
# Remarque : nécéssite XDot pour générer les graphiques

echo "Recherche de l'index de la documentation dans doc/html/ ...\n"

if [ ! -e "doc/html/index.html" ]; then
    echo "Documentation introuvable.\n"
	echo " -> Génération de la documentation\n"
	doxygen doc/doxyfile
	clear
else
    if [ $# = 1 ]; then
        if [ $1 = "actualiser" ]; then
            echo "Documentation trouvée.\n"
            echo "Suppression des fichiers existants.\n"
            cd doc/
            rm -f -r html/
            cd ../
            echo " -> Génération de la documentation.\n"
	        doxygen doc/doxyfile
	        clear
	    fi;
    fi;
fi;

echo "Ouverture de la documentation avec Firefox...\n"
firefox doc/html/index.html

